# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
r_github_packages:
  - r-lib/covr
cache: packages
after_success:
    - Rscript -e 'covr::codecov()'
