# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: release
r_github_packages:
  - r-lib/covr
  - jimhester/lintr
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package(linters = lintr::with_defaults(infix_spaces_linter = NULL, line_length_linter = lintr::line_length_linter(100)))'
