---
title: "Armageddon shock model distributions"
bibliography: ../inst/REFERENCES.bib
nocite: |
  @Mai2009a
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    eval = FALSE
)
```

The multivariate *armageddon shock model* family is a very simple example of a [mixture of Marshall–Olkin distributions](Mixing-Marshall-Olkin-distributions.html).

For a detailed mathematical treatment of this class, we refer to the references at the end of this document.

## Definition and survival function

We say that a random vector has  multivariate armageddon shock model distribution if there exist \( \lambda, \lambda^{G} \geq 0 \) with \( \lambda + \lambda^{G} > 0 \) such that for \( t_{[1]} \geq \cdots \geq t_{[d]} \)
\[
    \bar{F}{( \boldsymbol{t} )}
        = \exp{\left \{
                -{[ \lambda + \lambda^{G} ]} t_{[1]}
                -\lambda \sum_{i = 2}^{d}{
                    t_{[i]}
                }
            \right \}},
            \quad \boldsymbol{t} \geq 0 .
\]

This random vector has an exchangeable Marshall–Olkin distribution with parameters
\[
    \lambda_{I}
        = \begin{cases}
            \lambda         &   {\lvert I \rvert} = 1 , \\
            \lambda^{G}     &   {\lvert I \rvert} = d , \\
            0               &   \text{else} .
    \end{cases}
\]


## Stochastic model

The random vector can be generated by a [classical exogenous shock model](The-Marshall-Olkin-distribution.html#the-exogenous-shock-model),
by the [Arnold model](The-Marshall-Olkin-distribution.html#the-Arnold-shock-model) and [its exchangeable version](Exchangeable-Marshall-Olkin-distributions.html#fast-simulation),
by a Lévy frailty model with a killed subordinator with drift,
and by a [mixture of Marshall–Olkin distributions](Mixing-Marshall-Olkin-distributions.html).
In the latter case, one combines a vector of independent exponential distributed random variables with rate \( \lambda \) with a comonotone vector with exponential distributed random variables with rate \( \lambda^{G} \) via component-wise minima.

## References
