---
title: "The Lévy frailty model"
bibliography: ../inst/REFERENCES.bib
nocite: |
  @Mai2017a
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    eval = FALSE
)
```

A subclass of exchangeable Marshall–Olkin distributions can be sampled with a so-called *Lévy frailty model*.
This alternative stochastic model is very efficient in high dimensions.

For a detailed mathematical treatment of this class, we refer to the references at the end of this document.


## The extendible subclass

An exchangeable Marshall–Olkin distribution with parameters \( a_{0}, \ldots, a_{d-1} \) is called extendible if there exists a sequence \( \tau_{1}, \tau_{2}, \ldots \) such that each finite margin has a Marshall–Olkin distribution and
\[
    \mathbb{P}{\left( \tau_{1} > t_{1} , \ldots \tau_{d} > t_{d} \right)}
        = \exp{\left \{
                -\sum_{i = 0}^{d-1}{
                    a_{i} t_{[i+1]}
                }
            \right \}},
            \quad \boldsymbol{t} \geq 0 .
\]


## The Lévy frailty representation

Each extendible Marshall–Olkin distribution can be uniquely linked (in law) to a Lévy subordinator \( \Lambda \) and a iid unit exponential random variables \( E_{1}, \ldots , E_{d} \) such that \( \boldsymbol{\tau} \) has this distribution with
\[
    \tau_{i}
        = \inf{\left \{
                t > 0
                \ : \
                \Lambda_{t} \geq E_i
            \right \}},
            \quad i \in {\{ 1, \ldots, d \}} .
\]

If \( \psi \) is the Laplace exponent of the Lévy subordinator, i.e. \( \psi{(x)} = -\log\mathbb{E}{[\exp{\{ - x \Lambda_1\}}]} \), then
\[
    a_{i}
        = \psi{(i+1)} - \psi{(i)} ,
        \quad i \in {\{ 1, \ldots, d \}} .
\]


## Homogeneous Poisson process

A simple example is the case, when \( \Lambda \) is a homogenous Poisson process with rate \( \lambda > 0 \).
In this case
\[
    \psi{(x)}
        = \lambda {\left( 1 - \exp{\{ -x \}} \right)} ,
            \quad x \geq 0 .
\]


## Exponential killing and drift

Another simple example is the case, when the subordinator has a deterministic drift \( b \geq 0 \) and is killed (send to infinity) at a certain rate \( a \geq 0 \).
That means
\[
    \Lambda_{t}
        = N_{t}^{G} \cdot \infty + b t ,
            \quad t \geq 0 ,
\]
where \( N^{G} \) is a homogeneous Poisson process with rate \( a \).

We have
\[
    \psi{(x)}
        = a 1_{(0, \infty)}{(x)}
            + b x ,
            \quad x \geq 0 .
\]

This model produces a [multivariate armageddon shock model distribution](Armageddon-ESM-distribution.html).


## Compound Poisson process

The class of compound Poisson subordinators is the largest class of Lévy subordinators which can be used to sample *exactly* from a Marshall–Olkin distribution.
Here, the Lévy subordinator has the form
\[
    \Lambda_{t}
        = N_{t}^{G} \cdot \infty
            + b t
            + \sum_{i = 1}^{N_{t}} X_{i} ,
            \quad t \geq 0 ,
\]
where \( N^{G} \) is a homogeneous Poisson process with rate \( a \geq 0 \), \( b \geq 0 \) is a deterministic drift, \( N \) is a homogeneous Poisson process with rate \( \lambda \geq 0 \), and \( {\{ X_{i} \}}_{i \in \mathbb{N}} \) is an iid sequence of non-negative random variables (all objects are independent).

We have
\[
    \psi{(x)}
        = a 1_{(0, \infty)}{(x)}
            + b x
            + \lambda {\left( 1 - \mathcal{L}{(X_{1}; x)} \right)} ,
            \quad x \geq 0 ,
\]
where \( x \mapsto \mathcal{L}{(X_{1}, x)} \) is the Laplace transform of \( X_{1} \).


## References
