# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mo_internal__rexp <- function(n, rate = 1.) {
    .Call(`_rmo_mo_internal__rexp`, n, rate)
}

mo_internal__rpareto <- function(n, alpha, x0) {
    .Call(`_rmo_mo_internal__rpareto`, n, alpha, x0)
}

mo_internal__fixeddbl <- function(n, value) {
    .Call(`_rmo_mo_internal__fixeddbl`, n, value)
}

mo_internal__count_replace <- function(n, d, probabilities = NULL) {
    .Call(`_rmo_mo_internal__count_replace`, n, d, probabilities)
}

mo_internal__count_noreplace <- function(n, d, probabilities = NULL) {
    .Call(`_rmo_mo_internal__count_noreplace`, n, d, probabilities)
}

mo_internal__perm <- function(n) {
    .Call(`_rmo_mo_internal__perm`, n)
}

mo_internal__sample_int <- function(n, size, replace, prob = NULL, useHash = FALSE) {
    .Call(`_rmo_mo_internal__sample_int`, n, size, replace, prob, useHash)
}

#' @keywords internal helper
#' @noRd
Rcpp__is_within <- function(i, j) {
    .Call(`_rmo_Rcpp__is_within`, i, j)
}

#' @keywords internal
#' @noRd
NULL

#' @keywords internal
#' @noRd
Rcpp__rmo_esm <- function(n, d, intensities) {
    .Call(`_rmo_Rcpp__rmo_esm`, n, d, intensities)
}

#' @keywords internal
#' @noRd
Rcpp__rmo_arnold <- function(n, d, intensities) {
    .Call(`_rmo_Rcpp__rmo_arnold`, n, d, intensities)
}

#' @keywords internal
#' @noRd
Rcpp__rmo_ex_arnold <- function(n, d, ex_intensities) {
    .Call(`_rmo_Rcpp__rmo_ex_arnold`, n, d, ex_intensities)
}

#' @keywords internal
#' @noRd
Rcpp__rmo_esm_cuadras_auge <- function(n, d, alpha, beta) {
    .Call(`_rmo_Rcpp__rmo_esm_cuadras_auge`, n, d, alpha, beta)
}

#' @keywords internal
#' @noRd
Rcpp__rmo_lfm_cpp <- function(n, d, rate, rate_killing, rate_drift, rjump_name, rjump_arg_list) {
    .Call(`_rmo_Rcpp__rmo_lfm_cpp`, n, d, rate, rate_killing, rate_drift, rjump_name, rjump_arg_list)
}

