on:
  [push, pull_request]

name: Continuous Benchmarks

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes'))" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_github('r-lib/bench')"
          R CMD INSTALL .

      - name: Fetch existing benchmarks
        run: Rscript -e 'bench::cb_fetch()'

      - name: Run benchmarks
        run: Rscript -e 'bench::cb_run()'

      - name: Show benchmarks
        run: git notes --ref benchmarks show

      - name: Push benchmarks
        run: Rscript -e "bench::cb_push()"
